import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Sessionwrapper from "@/components/sessionwrapper";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Sessionwrapper>
      <Toaster />
        <body className={inter.className}>
        {children}
        </body>
        </Sessionwrapper>   
    </html>
  );
}
